import { readFile } from 'node:fs/promises';
import { join } from 'node:path';
import { homedir } from 'node:os';
const privatePath = process.argv[2];
if (!privatePath) throw new Error('Supply the existing service-account file path locally.');
const account = JSON.parse(await readFile(privatePath,'utf8'));
const auth = JSON.parse(await readFile(join(homedir(),'AppData/Roaming/com.vercel.cli/Data/auth.json'),'utf8'));
const local = await readFile('.env.local','utf8');
const vars = Object.fromEntries(local.split('\n').filter(line=>/^(VITE_FIREBASE_|CRON_SECRET=)/.test(line)).map(line=>{const pos=line.indexOf('=');return [line.slice(0,pos),line.slice(pos+1)];}));
Object.assign(vars,{FIREBASE_PROJECT_ID:account.project_id,FIREBASE_CLIENT_EMAIL:account.client_email,FIREBASE_PRIVATE_KEY:account.private_key});
const values = Object.entries(vars).map(([key,value])=>({key,value,type:key.startsWith('VITE_')?'plain':'sensitive',target:['production','preview']}));
const response = await fetch('https://api.vercel.com/v10/projects/prj_gwUEDAaOWfIF8ihEGiskovutznbU/env?upsert=true',{method:'POST',headers:{Authorization:`Bearer ${auth.token}`,'Content-Type':'application/json'},body:JSON.stringify(values)});
const result = await response.json();
if (!response.ok) throw new Error(`Environment setup failed (${response.status}): ${result.error?.code || 'Unknown'}`);
console.log(JSON.stringify({configuredKeys:values.map(x=>x.key),serverValuesPrinted:false,privateFileUploaded:false}));
